spring.application.name=backend
spring.datasource.url=jdbc:h2:file:./data/flights
spring.datasource.driverClassName=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true

spring.datasource.username=sa
spring.datasource.password=

server.port=${PORT:8080}

graph.service.url=${GRAPH_SERVICE_URL:http://localhost:8000}
airlines.file=${AIRLINES_FILE:../data/raw/airlines.dat}

# Graph service
graph.service.url=${GRAPH_SERVICE_URL:http://localhost:8000}
graph.service.connect-timeout=2s
graph.service.read-timeout=5s